main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('readings/', views.readings_index, name='index'),
    path('readings/<int:reading_id>/', views.readings_detail, name='detail' ),
    path('readings/create/', views.ReadingCreate.as_view(), name='readings_create'), 
    path('readings/<int:pk>/update/', views.ReadingUpdate.as_view(), name='readings_update'),
    path('readings/<int:pk>/delete/', views.ReadingDelete.as_view(), name='readings_delete'),
    path('readings/<int:reading_id>/add_bookmark', views.add_bookmark, name='add_bookmark'),
    path('readings/<int:reading_id>/assoc_badge/<int:badge_id>/', views.assoc_badge, name='assoc_badge'),
    path('readings/<int:reading_id>/unassoc_badge/<int:badge_id>/', views.unassoc_badge, name='unassoc_badge'),
    path('badges/', views.BadgeList.as_view(), name='badges_index'),
    path('badges/<int:pk>/', views.BadgeDetail.as_view(), name='badges_detail'),
    path('badges/create/', views.BadgeCreate.as_view(), name='badges_create'),
    path('badges/<int:pk>/update/', views.BadgeUpdate.as_view(), name='badges_update'),
    path('badges/<int:pk>/delete/', views.BadgeDelete.as_view(), name='badges_delete'),


]

readingcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# readings = [
#   reading('ULYSSES', 'Modernist novel', 'Ulysses is the story of a day in the life of Leopold Bloom as he travels Dublin and goes about his business, attending a funeral, buying soap, going to the Library, walking by the beach, going to the pub etc', 'James Joyce'),
#   reading('THE GREAT GATSBY', 'Tragedy, Realism, Modernism,', 'the tragic story of Jay Gatsby, a self-made millionaire, and his pursuit of Daisy Buchanan, a wealthy young woman whom he loved in his youth.', 'F. Scott Fitzgerald'),
#   reading('LOLITA', 'Novel', 'In Lolita, a middle-aged man named Humbert Humbert becomes obsessed with a pre-pubescent girl named Dolores Haze, who he calls Lolita. ', 'Vladimir Nabokov')
# ]

RANKS = (
    ('B', 'Bronze'),
    ('S', 'Silver'),
    ('G', 'Gold'),
)
class Badge(models.Model):
    name = models.CharField(max_length=100)
    rank = models.CharField(
        max_length=1,
        choices=RANKS,
        default=RANKS[0][0]
    )
    def __str__(self):
        return f'Badge {self.name} has Rank {self.get_rank_display()}'

    def get_absolute_url(self):
        return reverse('badges_detail', kwargs={'pk': self.id})
    


class Reading(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    description = models.TextField(max_length=2500)
    author = models.CharField(max_length=100)
    badges = models.ManyToManyField(Badge)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'reading_id': self.id})

class BookMark(models.Model):
    date = models.DateField('BookMark Date')
    chapter = models.IntegerField()
    # Create a cat_id FK
    reading = models.ForeignKey(Reading, on_delete=models.CASCADE)

    def __str__(self):
        return f"Chapter {self.chapter} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import BookMark

class BookMarkForm(ModelForm):
    class Meta:
        model = BookMark
        fields = ['date', 'chapter']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import  Reading, Badge
from .forms import BookMarkForm
# Define the home view

def home(request):
  return render( request, 'home.html')
def about(request):
    return render( request, 'about.html')

def readings_index(request):
  readings = Reading.objects.all()
  return render(request, 'readings/index.html', { 'readings': readings })

def readings_detail(request, reading_id):
  reading = Reading.objects.get(id=reading_id)
  id_list = reading.badges.all().values_list('id')
  badges_reading_doesnt_have = Badge.objects.exclude(id__in=id_list)
  bookmark_form = BookMarkForm()
  return render(request, 'readings/detail.html', {
    'reading': reading, 'bookmark_form': bookmark_form,
    'badges': badges_reading_doesnt_have
    })

class ReadingCreate(CreateView):
  model = Reading
  fields = ['title','genre','description', 'author']

class ReadingUpdate(UpdateView):
  model = Reading
  fields = ['genre', 'description', 'author']

class ReadingDelete(DeleteView):
  model = Reading
  success_url = '/readings/'

def add_bookmark(request, reading_id):
  form = BookMarkForm(request.POST)
  if form.is_valid():
    new_bookmark = form.save(commit=False)
    new_bookmark.reading_id = reading_id
    new_bookmark.save()
  return redirect('detail', reading_id=reading_id)

def assoc_badge(request, reading_id, badge_id):
  Reading.objects.get(id=reading_id).badges.add(badge_id)
  return redirect('detail', reading_id=reading_id)

def unassoc_badge(request, reading_id, badge_id):
  Reading.objects.get(id=reading_id).badges.remove(badge_id)
  return redirect('detail', reading_id=reading_id)

class BadgeList(ListView):
  model = Badge

class BadgeDetail(DetailView):
  model = Badge

class BadgeCreate(CreateView):
  model = Badge
  fields = "__all__"

class BadgeUpdate(UpdateView):
  model = Badge
  fields = "__all__"

class BadgeDelete(DeleteView):
  model = Badge
  success_url = '/badges/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Reading Collector</h1>
    <hr />
    <p>Hire the Reading Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Reading Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Reading Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'badges_create' %}">Create a Badge</a></li>
          <li><a href="{% url 'badges_index' %}">Badge List</a></li>
          <li><a href="{% url 'readings_create' %}">Add a Novel</a></li>
          <li><a href="{% url 'index' %}">View All My Novels</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Reading Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/badge_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'badges_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/badge_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Badge Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ badge.name }}</span>
        <p>Rank: {{ badge.get_rank_display }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'badges_update' badge.id %}">Edit</a>
        <a href="{% url 'badges_delete' badge.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/badge_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Badge</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

  <script>
    const selectEl = document.getElementById('id_rank');
    M.FormSelect.init(selectEl);
  </script>
{% endblock %}

main_app/templates/main_app/badge_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Badge List</h1>

{% for badge in badge_list %}
    <a href="{% url 'badges_detail' badge.id %}">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ badge.name }}</span>
                <p>rank: {{ badge.get_rank_display  }}</p>
            </div>
        </div>
    </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/reading_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Novel</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' reading.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/reading_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Novel</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/readings/detail.html
{% extends 'base.html' %}
{% block content %}


<h1>Novel Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ reading.title }}</span>
                <p>Genre: {{ reading.genre }}</p>
                <p>Description: {{ reading.description|linebreaks }}</p>
                <p>Author: {{ reading.author }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'readings_update' reading.id %}">Edit</a>
                <a href="{% url 'readings_delete' reading.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        
        <form action="{% url 'add_bookmark' reading.id %}" method="POST">
            {% csrf_token %}
            {{ bookmark_form.as_p }}
            <button class="btn" type="submit"> Add Bookmark</button>
          </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Chapter</th>
                </tr>
            </thead>
            <tbody>
                {% for bookmark in reading.bookmark_set.all %}
                <tr>
                    <td>{{bookmark.date}}</td>
                    <td>{{bookmark.chapter}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- This is all new markup to be added just above the <script> tag -->
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ reading.title }}'s Badges</h3> 
        {% if reading.badges.count %} 
            {% for badge in reading.badges.all %} 
            <div class="card">
                <div class="card-content">
                    <span class="card-title"> Rank(<span >{{ badge.get_rank_display }}</span>): {{ badge.name }}
                    </span>
                </div>
                <div class="card-action">
                    <form action="{% url 'unassoc_badge' reading.id badge.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">Remove</button>
                    </form>
                  </div>
            </div> 
            {% endfor %} 
        {% else %} 
        <h5>No Badge :(</h5>
        {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
        <h3>Available Badges</h3>
        {% if badges.count %}
            {% for badge in badges.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        Rank(<span >{{ badge.get_rank_display }}</span>): {{ badge.name }}
                    </span>
                </div>
                <div class="card-action">
                    <form action="{% url 'assoc_badge' reading.id badge.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">Add</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h5>{{reading.name}} Already Has All Badges Available</h5>
        {% endif %}
    </div>
</div>
<script>
const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/readings/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Novel List</h1>

{% for reading in readings %}
  <div class="card">
    <a href="{% url 'detail' reading.id %}">
    <div class="card-content">
      <span class="card-title">{{ reading.title }}</span>
      <p>Genre: {{ reading.genre }}</p>
      <p>Description: {{ reading.description }}</p>
        <p>Author: {{ reading.author }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}